version: '3'

networks:
  webapp:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
    - "82:80"
    links:
      - php-1
#      - php-2
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php-1
#      - php-2
      - postgres
    networks:
      - webapp

  php-1:
    build:
      context: ./docker/php-fpm-1
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php_1
    restart: always
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
    networks:
      - webapp

#  php-2:
#      build:
#          context: ./docker/php-fpm-2
#          dockerfile: Dockerfile
#      container_name: ${APP_NAME}_php_2
#      restart: always
#      volumes:
#          - ./:/var/www/html
#      depends_on:
#          - postgres
#      networks:
#          - webapp

  postgres:
    image: postgres:12.3-alpine
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    ports:
      - "6000:${FORWARD_DB_PORT:-5432}"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - webapp

  charts:
      image: ianw/quickchart
      ports:
        - "83:3400"
      networks:
          - webapp
