<?php

namespace Database\Seeders\BoilerRoom;

use App\Models\Address\Address;
use App\Models\BoilerRoom\BoilerRoom;
use App\Models\Meta\User\User;
use App\Models\Structure\StructureList\StructureList;
use App\Models\Structure\StructureList\StructureListValue\StructureListValue;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BoilerRoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user = User::where('login', 'admin')->first()->user_id;

        $boilerRoomsVolovskiy = [
            [
                'boiler_room_id' => Str::Uuid()->toString(), //
                'title' => 'котельная с. Волово', //
                'municipality' => 'Воловский', //
                'address' => 'Липецкая обл., с. Волово, ул. Советсткая, д.111', //
                'name_of_the_owner' => 'Администрация Воловского муниципального района',
                'operating_organization' => 'ООО "Теплосервис"', //
                'connected_homes' => 0, //
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0, //
                'connected_budgets' => 6, //
                'summ_heating_supply_for_social' => 1.242,
                'summ_hot_water_supply_for_social' => 0.0, //
                'connected_others' => 5,
                'summ_heating_supply_others' => 0.127,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 1.89, //
                'seasonality_of_work' => 'отопительный период', //
                'mode' => 'временное присутствие персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
        ];

        $boilerRoomsTerbunsky = [
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'котельная с.Тербуны',
                'municipality' => 'Тербунский',
                'address' => 'Липецкая обл., Тербунский р-н., с. Тербуны, ул. Красноармейская, 4',
                'name_of_the_owner' => 'Направление имущественных и земельных отношений Липецкой области',
                'operating_organization' => 'ООО "Теплосервис"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 13,
                'summ_heating_supply_for_social' => 2.725,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 1,
                'summ_heating_supply_others' => 0.007456,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 3.024,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'временное присутствие персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
        ];

        $boilerRoomsDankovsky = [
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'котельная администрации Данковского района',
                'municipality' => 'Данковский',
                'address' => 'г. Данков, ул. Семеновского, д.13',
                'name_of_the_owner' => 'администрация Данковского района',
                'operating_organization' => 'Администрация Данковского муниципального района',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 260,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'котельная администрации сельского поселения Баловневский с/с',
                'municipality' => 'Данковский',
                'address' => 'с.Баловнево ул. Новосоветская д.14',
                'name_of_the_owner' => 'администрация сельского поселения Баловневский с/с',
                'operating_organization' => 'ООО «Газпром межрегионгаз Липецк»',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 23,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'котельная МБУК "ПЦК и Д" с. Баловнево',
                'municipality' => 'Данковский',
                'address' => 'с.Баловнево ул. Советская д.15',
                'name_of_the_owner' => 'МБУК "ПЦКиД"  сельского поселения  Баловневский с/с',
                'operating_organization' => 'МБУК "ПЦКиД"  сельского поселения  Баловневский с/с',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 0.105341,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'с персоналом',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная СДК с. Телепнево',
                'municipality' => 'Данковский',
                'address' => 'с. Телепнево ул. Советская д.1',
                'name_of_the_owner' => 'МБУК "ПЦКд" с/п Баловневский с/с',
                'operating_organization' => 'МБУК "ПЦКд" с/п Баловневский с/с',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 0.0688,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'с персоналом',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная СДК с. Хрущево - Подлесное',
                'municipality' => 'Данковский',
                'address' => 'с.Хрущево - Подлесное ул. Центральная д.1/1',
                'name_of_the_owner' => 'МБУК "ПЦКд" с/п Баловневский с/с',
                'operating_organization' => 'МБУК "ПЦКд" с/п Баловневский с/с',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 0.06,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'с персоналом',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
        ];

        $boilerRoomsLipetsky = [
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Акционерное общество "Транснефть-Дружба" ',
                'municipality' => 'Липецкий',
                'address' => 'Котельная, Липецкий р-н, с. Сухая Лубна, ул. Молодежная',
                'name_of_the_owner' => 'Акционерное общество "Транснефть-Дружба" ',
                'operating_organization' => 'Акционерное общество "Транснефть-Дружба" ',
                'connected_homes' => 3,
                'summ_heating_supply_for_homes' => 0.1,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 4.3,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Акционерное общество Продовольственная компания "ЛИМАК"',
                'municipality' => 'Липецкий',
                'address' => 'Котельная, Липецкий р-н, с. Подгорное, ул. Элеваторная, д. 1',
                'name_of_the_owner' => 'Акционерное общество Продовольственная компания "ЛИМАК"',
                'operating_organization' => 'Акционерное общество Продовольственная компания "ЛИМАК"',
                'connected_homes' => 3,
                'summ_heating_supply_for_homes' => 0.55,
                'summ_hot_water_supply_for_homes' => 0.55,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 7.7,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная Васильевский ФАП  ',
                'municipality' => 'Липецкий',
                'address' => 'Васильевский ФАП, Липецкая область, Липецкий р-н, с. Васильевка, пер. Тихий, д.7',
                'name_of_the_owner' => 'Управление земельных и имущественных отношений Липецкой области',
                'operating_organization' => 'ГУЗ "Липецкая районная больница"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.009,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 0.009,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Вешаловский ФАП, Липецкая обл., Липецкий р-н, с. Вешаловка, ул. 8 Марта, д. 56а',
                'municipality' => 'Липецкий',
                'address' => 'Вешаловский ФАП, Липецкая обл., Липецкий р-н, с. Вешаловка, ул. 8 Марта, д. 56а',
                'name_of_the_owner' => 'Управление земельных и имущественных отношений Липецкой области',
                'operating_organization' => 'ГУЗ "Липецкая районная больница"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.09,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 0.009,
                'seasonality_of_work' => 'отопителый период',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная Грязновский ФАП  ',
                'municipality' => 'Липецкий',
                'address' => 'Грязновский ФАП, Липецкая область, Липецкий р-н, с. Грязное, ул. Ленинская, д. 27',
                'name_of_the_owner' => 'Управление земельных и имущественных отношений Липецкой области',
                'operating_organization' => 'ГУЗ "Липецкая районная больница"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.019,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 0.019,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
        ];

        $boilerRoomsChaplyginsky = [
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'СЦТ "Котельная  (БМК 5,65)',
                'municipality' => 'Чаплыгинский',
                'address' => 'г.Чаплыгин ул. Московская, 7а',
                'name_of_the_owner' => 'Администрация Чаплыгинского  района',
                'operating_organization' => 'АО "Раненбург-Теплосервис"',
                'connected_homes' => 17,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 4,
                'summ_heating_supply_for_social' => 0.9879,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 1,
                'summ_heating_supply_others' => 0.112,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 5.65,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'СЦТ "Котельная  (1,08 Гкал/час)" совхоз-колледж',
                'municipality' => 'Чаплыгинский',
                'address' => 'г.Чаплыгин  ул. Советская, 11',
                'name_of_the_owner' => 'Администрация Чаплыгинского  района',
                'operating_organization' => 'АО "Раненбург-Теплосервис"',
                'connected_homes' => 3,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 1.08,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'СЦТ "Котельная  (6,45 Гкал/час)" УМГ',
                'municipality' => 'Чаплыгинский',
                'address' => 'г.Чаплыгин  ул. Советская',
                'name_of_the_owner' => 'Администрация Чаплыгинского  района',
                'operating_organization' => 'АО "Раненбург-Теплосервис"',
                'connected_homes' => 7,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 3,
                'summ_heating_supply_for_social' => 0.2655,
                'summ_hot_water_supply_for_social' => 0.0098,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 6.45,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'СЦТ "Котельная  (БМК 1,2)',
                'municipality' => 'Чаплыгинский',
                'address' => 'г.Чаплыгин Московский 8а',
                'name_of_the_owner' => 'Администрация Чаплыгинского  района',
                'operating_organization' => 'АО "Раненбург-Теплосервис"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 2,
                'summ_heating_supply_for_social' => 0.3136,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 3,
                'summ_heating_supply_others' => 0.6216,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 1.2,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'СЦТ "Котельная  (БМК 1,0)',
                'municipality' => 'Чаплыгинский',
                'address' => 'г.Чаплыгин  ул.Крупской 52а"',
                'name_of_the_owner' => 'Администрация Чаплыгинского  района',
                'operating_organization' => 'АО "Раненбург-Теплосервис"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 2,
                'summ_heating_supply_for_social' => 0.5754,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 1,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
        ];

        $boilerRoomsGrazy = [
            [
                'boiler_room_id' => Str::Uuid()->toString(),
                'title' => '"Первомайская"',
                'municipality' => 'Грязинский',
                'address' => 'г. Грязи, ул. Первомайская, 65',
                'name_of_the_owner' => 'Администрация городского поселения г. Грязи Грязинского муниципального района Липецкой области',
                'operating_organization' => 'ПАО "Квадра"',
                'connected_homes' => 43,
                'summ_heating_supply_for_homes' => 6.794787,
                'summ_hot_water_supply_for_homes' => 1.1613,
                'connected_budgets' => 20,
                'summ_heating_supply_for_social' => 1.630713,
                'summ_hot_water_supply_for_social' => 0.031189,
                'connected_others' => 47,
                'summ_heating_supply_others' => 1.556604,
                'summ_hot_water_supply_others' => 0.222344,
                'installed_capacity' => 19.5,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user
            ],
            [
                'boiler_room_id' => Str::Uuid()->toString(),
                'title' => '"ЦРБ"',
                'municipality' => 'Грязинский',
                'address' => 'г. Грязи, ул. Социалистическая, 3',
                'name_of_the_owner' => 'Администрация городского поселения г. Грязи Грязинского муниципального района Липецкой области',
                'operating_organization' => 'ПАО "Квадра"',
                'connected_homes' => 8,
                'summ_heating_supply_for_homes' => 1.2361,
                'summ_hot_water_supply_for_homes' => 0.1848,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.64713,
                'summ_hot_water_supply_for_social' => 0.022786,
                'connected_others' => 3,
                'summ_heating_supply_others' => 0.058148,
                'summ_hot_water_supply_others' => 0.000154,
                'installed_capacity' => 6.4,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user
            ],
            [
                'boiler_room_id' => Str::Uuid()->toString(),
                'title' => '"Швейная фабрика"',
                'municipality' => 'Грязинский',
                'address' => 'г. Грязи, ул. 30 лет Победы, 52',
                'name_of_the_owner' => 'Администрация городского поселения г. Грязи Грязинского муниципального района Липецкой области',
                'operating_organization' => 'ПАО "Квадра"',
                'connected_homes' => 16,
                'summ_heating_supply_for_homes' => 1.577764,
                'summ_hot_water_supply_for_homes' => 0.078029,
                'connected_budgets' => 8,
                'summ_heating_supply_for_social' => 0.430501,
                'summ_hot_water_supply_for_social' => 0.000253,
                'connected_others' => 18,
                'summ_heating_supply_others' => 0.958437,
                'summ_hot_water_supply_others' => 0.081527,
                'installed_capacity' => 7,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user
            ],
            [
                'boiler_room_id' => Str::Uuid()->toString(),
                'title' => '"ГПТУ"',
                'municipality' => 'Грязинский',
                'address' => 'г. Грязи, ул. Юбилейная, 3',
                'name_of_the_owner' => 'Администрация городского поселения г. Грязи Грязинского муниципального района Липецкой области',
                'operating_organization' => 'ПАО "Квадра"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 2,
                'summ_heating_supply_for_social' => 0.349324,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 3.2,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user
            ],
            [
                'boiler_room_id' => Str::Uuid()->toString(),
                'title' => 'Котельная школы № 8',
                'municipality' => 'Грязинский',
                'address' => 'г. Грязи, ул. Привокзальная, 2а',
                'name_of_the_owner' => 'Администрация городского поселения г. Грязи Грязинского муниципального района Липецкой области',
                'operating_organization' => 'ПАО "Квадра"',
                'connected_homes' => 1,
                'summ_heating_supply_for_homes' => 0.0739,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 2,
                'summ_heating_supply_for_social' => 0.118198,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 0.43,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user
            ],
        ];

        $boilerRoomsDobrobkiy = [
            [
                'boiler_room_id' => Str::Uuid()->toString(),
                'title' => 'котельная с.Доброе ул.Победы,13',
                'municipality' => 'Добровский',
                'address' => 'Липекая область с.Доброе ул.Победы ,13',
                'name_of_the_owner' => 'ЛОКК',
                'operating_organization' => 'АО "Ранебург-теплосервис"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 4,
                'summ_heating_supply_for_social' => 2.0,
                'summ_hot_water_supply_for_social' => 0.5,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 3,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
        ];

        $boilerRoomsUsmanskiy = [
            [
                'boiler_room_id' => Str::Uuid()->toString(),
                'title' => 'АБМК',
                'municipality' => 'Усманский',
                'address' => 'с. Пригородка ул. Лесная,4',
                'name_of_the_owner' => 'администрация Усманского района',
                'operating_organization' => 'ООО "Теплосервис"',
                'connected_homes' => 4,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 1,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 1.1,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с персоналом',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::Uuid()->toString(),
                'title' => 'ЦРБ',
                'municipality' => 'Усманский',
                'address' => 'г.Усмань, ул. Карла Маркса, 118',
                'name_of_the_owner' => 'администрация г.Усмань',
                'operating_organization' => 'ООО "Теплосервис"',
                'connected_homes' => 8,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 7,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 6.4,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с персоналом',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::Uuid()->toString(),
                'title' => 'АБМК-14',
                'municipality' => 'Усманский',
                'address' => 'г. Усмань, ул.Льва Толстого,95а',
                'name_of_the_owner' => 'администрация г.Усмань',
                'operating_organization' => 'ООО "Теплосервис"',
                'connected_homes' => 47,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 6,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 6,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 12.04,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с персоналом',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::Uuid()->toString(),
                'title' => 'АБМК-2',
                'municipality' => 'Усманский',
                'address' => 'г.Усмань, ул.Чернышевскрго,123в',
                'name_of_the_owner' => 'администрация г.Усмань',
                'operating_organization' => 'ООО "Теплосервис"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 5,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 2,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 1.5,
                'seasonality_of_work' => 'межотопительный период',
                'mode' => 'с персоналом',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::Uuid()->toString(),
                'title' => 'топочная ЦРБ',
                'municipality' => 'Усманский',
                'address' => 'г. Усмань, ул.Комсомольская,22',
                'name_of_the_owner' => 'администрация г.Усмань',
                'operating_organization' => 'ООО "Теплосервис"',
                'connected_homes' => 1,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 0.2,
                'seasonality_of_work' => 'межотопительный период',
                'mode' => 'с персоналом',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
        ];

        $boilerRoomsLipetsk = [
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'котельная студеновской промплощадки АО "Стагдок"',
                'municipality' => 'г. Липецк',
                'address' => 'г. Липецк р-он ул. К. Цеткин',
                'name_of_the_owner' => 'АО "Стагдок"',
                'operating_organization' => 'АО "Стагдок"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 2.15,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'с персоналом',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Автономная котельная водогрейная',
                'municipality' => 'г. Липецк',
                'address' => 'г. Липецк, ул.Бородинская, строение 49',
                'name_of_the_owner' => 'ООО "Климат-Л"',
                'operating_organization' => 'ООО "ЭнергоПлюс"',
                'connected_homes' => 7,
                'summ_heating_supply_for_homes' => 3.41,
                'summ_hot_water_supply_for_homes' => 2.31,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 1,
                'summ_heating_supply_others' => 0.3,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 7.64,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'котельная ТКУ-10,7 ТРК Ривьера',
                'municipality' => 'г. Липецк',
                'address' => 'г. Липецк ул. Катукова, влад. 51',
                'name_of_the_owner' => 'ООО "ТТЦ "ФОЛИУМ"',
                'operating_organization' => 'ООО "Энергосбыт"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 1,
                'summ_heating_supply_others' => 9.12,
                'summ_hot_water_supply_others' => 0.8,
                'installed_capacity' => 10.7,
                'seasonality_of_work' => 'весь год',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'котельная ТКУ-4.0',
                'municipality' => 'г. Липецк',
                'address' => 'г. Липецк ул. Гагарина 70 а',
                'name_of_the_owner' => 'ООО "Мегаполис - Недвижимость"',
                'operating_organization' => 'ООО "Мегаполис - Недвижимость"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 2,
                'summ_heating_supply_for_social' => 2.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 3.44,
                'seasonality_of_work' => 'отопительный сезон',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'котельная "КОМУС"',
                'municipality' => 'г. Липецк',
                'address' => 'г. Липецк ул. 8 Марта, строение 15б',
                'name_of_the_owner' => 'ООО "КОМУС"',
                'operating_organization' => 'ООО "Теплогарант"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 11,
                'summ_heating_supply_others' => 5.43,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 5.59,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'котельная с теплотрассой',
                'municipality' => 'г. Липецк',
                'address' => 'г. Липецк ул. Тамбовская, д. 8',
                'name_of_the_owner' => 'ООО "Зем Рем Строй Липецк"',
                'operating_organization' => 'ООО "Зем Рем Строй Липецк"',
                'connected_homes' => 1,
                'summ_heating_supply_for_homes' => 0.98,
                'summ_hot_water_supply_for_homes' => 0.98,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 0.98,
                'seasonality_of_work' => 'весь год',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'котельная студеновской промплощадки АО "Стагдок"',
                'municipality' => 'г. Липецк',
                'address' => 'г. Липецк р-он ул. К. Цеткин',
                'name_of_the_owner' => 'АО "Стагдок"',
                'operating_organization' => 'АО "Стагдок"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0.0,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0.0,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 2.15,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'с персоналом',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная №1',
                'municipality' => 'г. Липецк',
                'address' => 'г. Липецк ул. С.Казьмина, д.3а',
                'name_of_the_owner' => 'АО "Домостроительный комбинат"',
                'operating_organization' => 'ООО "ЭнергоКонсалт"',
                'connected_homes' => 17,
                'summ_heating_supply_for_homes' => 12.478,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 8,
                'summ_heating_supply_others' => 3.421,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 6.36,
                'seasonality_of_work' => 'весь год',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная №2',
                'municipality' => 'г. Липецк',
                'address' => 'г. Липецк ул. С.Казьмина, д.3а/1',
                'name_of_the_owner' => 'АО "Домостроительный комбинат"',
                'operating_organization' => 'ООО "ЭнергоКонсалт"',
                'connected_homes' => 17,
                'summ_heating_supply_for_homes' => 12.478,
                'summ_hot_water_supply_for_homes' => 0.0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0.0,
                'summ_hot_water_supply_for_social' => 0.0,
                'connected_others' => 8,
                'summ_heating_supply_others' => 3.421,
                'summ_hot_water_supply_others' => 0.0,
                'installed_capacity' => 14.53,
                'seasonality_of_work' => 'весь год',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
        ];

        $boilerRoomsElets = [
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная СЦТ',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул. Новолипецкая, 1Д',
                'name_of_the_owner' => 'Администрация г. Ельца',
                'operating_organization' => 'ООО "Мегастрой"',
                'connected_homes' => 14,
                'summ_heating_supply_for_homes' => 3.334,
                'summ_hot_water_supply_for_homes' => 1.206,
                'connected_budgets' => 2,
                'summ_heating_supply_for_social' => 0.13,
                'summ_hot_water_supply_for_social' => 0.029,
                'connected_others' => 3,
                'summ_heating_supply_others' => 0.586,
                'summ_hot_water_supply_others' => 0.115,
                'installed_capacity' => 5.504,
                'seasonality_of_work' => 'весь год',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная СЦТ',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул. Новолипецкая, 3В',
                'name_of_the_owner' => 'Администрация г. Ельца',
                'operating_organization' => 'ООО "Мегастрой"',
                'connected_homes' => 8,
                'summ_heating_supply_for_homes' => 0.923,
                'summ_hot_water_supply_for_homes' => 0.488,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.05,
                'summ_hot_water_supply_for_social' => 0.002,
                'connected_others' => 3,
                'summ_heating_supply_others' => 0.017,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 3.03,
                'seasonality_of_work' => 'весь год',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная СЦТ',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул. Новолипецкая, 1П',
                'name_of_the_owner' => 'Администрация г. Ельца',
                'operating_organization' => 'ООО "Мегастрой"',
                'connected_homes' => 1,
                'summ_heating_supply_for_homes' => 0.105,
                'summ_hot_water_supply_for_homes' => 0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0,
                'summ_hot_water_supply_for_social' => 0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 3.03,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная СЦТ',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул Мира, 124В',
                'name_of_the_owner' => 'Администрация г. Ельца',
                'operating_organization' => 'ООО "Мегастрой"',
                'connected_homes' => 1,
                'summ_heating_supply_for_homes' => 0.10,
                'summ_hot_water_supply_for_homes' => 0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0,
                'summ_hot_water_supply_for_social' => 0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 0.164,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная СЦТ',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул. Л. Толстого, 4В',
                'name_of_the_owner' => 'Администрация г. Ельца',
                'operating_organization' => 'ООО "Мегастрой"',
                'connected_homes' => 2,
                'summ_heating_supply_for_homes' => 0.116,
                'summ_hot_water_supply_for_homes' => 0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0,
                'summ_hot_water_supply_for_social' => 0,
                'connected_others' => 1,
                'summ_heating_supply_others' => 0.004,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 0.43,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная СЦТ',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул. Свердлова, 7В',
                'name_of_the_owner' => 'Администрация г. Ельца',
                'operating_organization' => 'ООО "Мегастрой"',
                'connected_homes' => 1,
                'summ_heating_supply_for_homes' => 0.03,
                'summ_hot_water_supply_for_homes' => 0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0,
                'summ_hot_water_supply_for_social' => 0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 0.164,
                'seasonality_of_work' => 'отопительный сезон',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная СЦТ',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул 9 Декабря, 19В',
                'name_of_the_owner' => 'Администрация г. Ельца',
                'operating_organization' => 'ООО "Мегастрой"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0,
                'summ_hot_water_supply_for_homes' => 0,
                'connected_budgets' => 2,
                'summ_heating_supply_for_social' => 0.15,
                'summ_hot_water_supply_for_social' => 0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 0.246,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная СЦТ',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул Шоссейная, 1Б',
                'name_of_the_owner' => 'Администрация г. Ельца',
                'operating_organization' => 'ООО "Мегастрой"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0,
                'summ_hot_water_supply_for_homes' => 0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.10,
                'summ_hot_water_supply_for_social' => 0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 0.246,
                'seasonality_of_work' => 'весь год',
                'mode' => 'без персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная  ул. Ростовская, 1',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул. Ростовская, 1',
                'name_of_the_owner' => 'Управление имущественных и земельных отношений Липецкой области',
                'operating_organization' => 'ООО "Теплосервис"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0,
                'summ_hot_water_supply_for_homes' => 0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 2.715,
                'summ_hot_water_supply_for_social' => 0.102,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 0.86,
                'seasonality_of_work' => 'весь год',
                'mode' => 'постоянное присутствие персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная ул. Мира, 82',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул. Мира, 82',
                'name_of_the_owner' => 'ГОБПОУ "ЕГКИ им. Т.Н.Хренникова"',
                'operating_organization' => 'ООО "Теплосервис"',
                'connected_homes' => 0,
                'summ_heating_supply_for_homes' => 0,
                'summ_hot_water_supply_for_homes' => 0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.057,
                'summ_hot_water_supply_for_social' => 0,
                'connected_others' => 0,
                'summ_heating_supply_others' => 0,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 0.172,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'временное присутствие персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная ул. Пушкина, 123',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул. Пушкина, 123',
                'name_of_the_owner' => 'Администрация городского округа г. Елец',
                'operating_organization' => 'ООО "Теплосервис"',
                'connected_homes' => 2,
                'summ_heating_supply_for_homes' => 0.35,
                'summ_hot_water_supply_for_homes' => 0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.001,
                'summ_hot_water_supply_for_social' => 0,
                'connected_others' => 1,
                'summ_heating_supply_others' => 0.01,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 0.516,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'временное присутствие персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная ул. Маяковского, 1',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул. Маяковского, 1',
                'name_of_the_owner' => 'Администрация городского округа г. Елец',
                'operating_organization' => 'ООО "Теплосервис"',
                'connected_homes' => 4,
                'summ_heating_supply_for_homes' => 0.93,
                'summ_hot_water_supply_for_homes' => 0,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.01,
                'summ_hot_water_supply_for_social' => 0,
                'connected_others' => 1,
                'summ_heating_supply_others' => 0.01355,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 1.08,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'временное присутствие персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная пл. Победы, 1',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, пл. Победы, 1',
                'name_of_the_owner' => 'Управление имущественных и земельных отношений Липецкой области',
                'operating_organization' => 'ООО "Теплосервис"',
                'connected_homes' => 3,
                'summ_heating_supply_for_homes' => 1.7,
                'summ_hot_water_supply_for_homes' => 0,
                'connected_budgets' => 0,
                'summ_heating_supply_for_social' => 0,
                'summ_hot_water_supply_for_social' => 0,
                'connected_others' => 2,
                'summ_heating_supply_others' => 0.023,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 1.73,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'временное присутствие персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная ул. Мира, 94',
                'municipality' => 'г. Елец',
                'address' => 'г. Елец, ул. Мира, 94',
                'name_of_the_owner' => 'Управление имущественных и земельных отношений Липецкой области',
                'operating_organization' => 'ООО "Теплосервис"',
                'connected_homes' => 2,
                'summ_heating_supply_for_homes' => 0.11,
                'summ_hot_water_supply_for_homes' => 0,
                'connected_budgets' => 4,
                'summ_heating_supply_for_social' => 0.303,
                'summ_hot_water_supply_for_social' => 0,
                'connected_others' => 2,
                'summ_heating_supply_others' => 0.0432,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 0.86,
                'seasonality_of_work' => 'отопительный период',
                'mode' => 'временное присутствие персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Елецкая ТЭЦ (г.Елец, пос. ТЭЦ)',
                'municipality' => 'г. Елец',
                'address' => 'г.Елец, пос. ТЭЦ',
                'name_of_the_owner' => 'ПАО "Квадра"',
                'operating_organization' => 'ПАО "Квадра"',
                'connected_homes' => 216,
                'summ_heating_supply_for_homes' => 49.135,
                'summ_hot_water_supply_for_homes' => 4.759,
                'connected_budgets' => 41,
                'summ_heating_supply_for_social' => 9.231,
                'summ_hot_water_supply_for_social' => 0.455,
                'connected_others' => 195,
                'summ_heating_supply_others' => 20.596,
                'summ_hot_water_supply_others' => 0.327,
                'installed_capacity' => 148,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
            [
                'boiler_room_id' => Str::uuid()->toString(),
                'title' => 'Котельная сл.Александровка (г.Елец, сл.Александровка)',
                'municipality' => 'г. Елец',
                'address' => 'г.Елец, сл.Александровка',
                'name_of_the_owner' => 'ОГУП "ЛОКК"',
                'operating_organization' => 'ПАО "Квадра"',
                'connected_homes' => 7,
                'summ_heating_supply_for_homes' => 1.896,
                'summ_hot_water_supply_for_homes' => 0.079,
                'connected_budgets' => 1,
                'summ_heating_supply_for_social' => 0.797,
                'summ_hot_water_supply_for_social' => 0,
                'connected_others' => 8,
                'summ_heating_supply_others' => 0.203,
                'summ_hot_water_supply_others' => 0,
                'installed_capacity' => 4.5,
                'seasonality_of_work' => 'весь год',
                'mode' => 'с постоянным присутствием персонала',
                'owner_id' => $user,
                'created_by' => $user,
                'updated_by' => $user,
            ],
        ];

        BoilerRoom::insert($boilerRoomsLipetsk);
        BoilerRoom::insert($boilerRoomsElets);
        BoilerRoom::insert($boilerRoomsVolovskiy);
        BoilerRoom::insert($boilerRoomsGrazy);
        BoilerRoom::insert($boilerRoomsDobrobkiy);
        BoilerRoom::insert($boilerRoomsUsmanskiy);
        BoilerRoom::insert($boilerRoomsTerbunsky);
        BoilerRoom::insert($boilerRoomsDankovsky);
        BoilerRoom::insert($boilerRoomsLipetsky);
        BoilerRoom::insert($boilerRoomsChaplyginsky);
    }
}
