<?php

namespace Database\Seeders\BoilerRoom;

use App\Models\BoilerRoom\BoilerRoomConsumer\BoilerRoomConsumer;
use App\Models\Meta\User\User;
use Illuminate\Database\Seeder;
use Str;

class BoilerRoomConsumerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user_value_1 = User::where('login', '1')->first()->user_id;

        $user_value_2 = User::where('login', '2')->first()->user_id;

        $user_value_3 = User::where('login', '3')->first()->user_id;

        $user_value_4 = User::where('login', '4')->first()->user_id;

        $user_value_5 = User::where('login', '5')->first()->user_id;

        $user_value_6 = User::where('login', '6')->first()->user_id;

        $user_value_7 = User::where('login', '7')->first()->user_id;

        $user_value_8 = User::where('login', '8')->first()->user_id;

        $user_value_9 = User::where('login', '9')->first()->user_id;

        $user_value_10 = User::where('login', '10')->first()->user_id;

        $user_value_11 = User::where('login', '11')->first()->user_id;

        $user_value_12 = User::where('login', '12')->first()->user_id;

        $user_value_13 = User::where('login', '13')->first()->user_id;

        $user_value_14 = User::where('login', '14')->first()->user_id;

        $user_value_15 = User::where('login', '15')->first()->user_id;

        $user_value_16 = User::where('login', '16')->first()->user_id;

        $user_value_17 = User::where('login', '17')->first()->user_id;

        $user_value_18 = User::where('login', '18')->first()->user_id;

        $user_value_19 = User::where('login', '19')->first()->user_id;

        $user_value_20 = User::where('login', '20')->first()->user_id;

        BoilerRoomConsumer::insert([
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_1,
                'created_by' => $user_value_1,
                'updated_by' => $user_value_1,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0.1,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_2,
                'created_by' => $user_value_2,
                'updated_by' => $user_value_2,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0.55,
                'heating' => 0.55,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_4,
                'created_by' => $user_value_4,
                'updated_by' => $user_value_4,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0.027,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_5,
                'created_by' => $user_value_5,
                'updated_by' => $user_value_5,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_6,
                'created_by' => $user_value_6,
                'updated_by' => $user_value_6,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_7,
                'created_by' => $user_value_7,
                'updated_by' => $user_value_7,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0.172,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_8,
                'created_by' => $user_value_8,
                'updated_by' => $user_value_8,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0.7,
                'heating' => 1.5,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_4,
                'created_by' => $user_value_4,
                'updated_by' => $user_value_4,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0.344,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_9,
                'created_by' => $user_value_9,
                'updated_by' => $user_value_9,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0.4,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_10,
                'created_by' => $user_value_10,
                'updated_by' => $user_value_10,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 10.5,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_11,
                'created_by' => $user_value_11,
                'updated_by' => $user_value_11,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0.065,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_4,
                'created_by' => $user_value_4,
                'updated_by' => $user_value_4,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_12,
                'created_by' => $user_value_12,
                'updated_by' => $user_value_12,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_14,
                'created_by' => $user_value_14,
                'updated_by' => $user_value_14,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_15,
                'created_by' => $user_value_15,
                'updated_by' => $user_value_15,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_16,
                'created_by' => $user_value_16,
                'updated_by' => $user_value_16,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_17,
                'created_by' => $user_value_17,
                'updated_by' => $user_value_17,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_18,
                'created_by' => $user_value_18,
                'updated_by' => $user_value_18,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_19,
                'created_by' => $user_value_19,
                'updated_by' => $user_value_19,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
            [
                'boiler_room_consumer_id' => Str::Uuid()->toString(),
                'title' => ' ',
                'owner_id' => $user_value_20,
                'created_by' => $user_value_20,
                'updated_by' => $user_value_20,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'hot_water_supply' => 0,
                'heating' => 0,
            ],
        ]);
    }
}
