<?php

namespace Database\Seeders\BoilerRoom;

use App\Models\BoilerRoom\BoilerRoomHeatingNetwork\HeatingNetworkAccident\HeatingNetworkAccident;
use App\Models\Meta\User\User;
use Illuminate\Database\Seeder;
use Str;

class HeatingNetworkAccidentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user_value_1 = User::where('login', '1')->first()->user_id;

        $user_value_2 = User::where('login', '2')->first()->user_id;

        $user_value_3 = User::where('login', '3')->first()->user_id;

        $user_value_4 = User::where('login', '4')->first()->user_id;

        $user_value_5 = User::where('login', '5')->first()->user_id;

        $user_value_6 = User::where('login', '6')->first()->user_id;

        $user_value_7 = User::where('login', '7')->first()->user_id;

        $user_value_8 = User::where('login', '8')->first()->user_id;

        $user_value_9 = User::where('login', '9')->first()->user_id;

        $user_value_10 = User::where('login', '10')->first()->user_id;

        $user_value_11 = User::where('login', '11')->first()->user_id;

        $user_value_12 = User::where('login', '12')->first()->user_id;

        $user_value_13 = User::where('login', '13')->first()->user_id;

        $user_value_14 = User::where('login', '14')->first()->user_id;

        $user_value_15 = User::where('login', '15')->first()->user_id;

        $user_value_16 = User::where('login', '16')->first()->user_id;

        $user_value_17 = User::where('login', '17')->first()->user_id;

        $user_value_18 = User::where('login', '18')->first()->user_id;

        $user_value_19 = User::where('login', '19')->first()->user_id;

        $user_value_20 = User::where('login', '20')->first()->user_id;

        $user_value_null = User::where('login', 'null')->first()->user_id;

        HeatingNetworkAccident::insert([

            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_1,
                'created_by' => $user_value_1,
                'updated_by' => $user_value_1,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 1,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],


            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_3,
                'created_by' => $user_value_3,
                'updated_by' => $user_value_3,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_4,
                'created_by' => $user_value_4,
                'updated_by' => $user_value_4,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_5,
                'created_by' => $user_value_5,
                'updated_by' => $user_value_5,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_6,
                'created_by' => $user_value_6,
                'updated_by' => $user_value_6,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_7,
                'created_by' => $user_value_7,
                'updated_by' => $user_value_7,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_8,
                'created_by' => $user_value_8,
                'updated_by' => $user_value_8,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_4,
                'created_by' => $user_value_4,
                'updated_by' => $user_value_4,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_9,
                'created_by' => $user_value_9,
                'updated_by' => $user_value_9,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_10,
                'created_by' => $user_value_10,
                'updated_by' => $user_value_10,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_11,
                'created_by' => $user_value_11,
                'updated_by' => $user_value_11,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_4,
                'created_by' => $user_value_4,
                'updated_by' => $user_value_4,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_12,
                'created_by' => $user_value_12,
                'updated_by' => $user_value_12,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => '2018',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => '1998',
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_13,
                'created_by' => $user_value_13,
                'updated_by' => $user_value_13,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_14,
                'created_by' => $user_value_14,
                'updated_by' => $user_value_14,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_15,
                'created_by' => $user_value_15,
                'updated_by' => $user_value_15,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_16,
                'created_by' => $user_value_16,
                'updated_by' => $user_value_16,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_17,
                'created_by' => $user_value_17,
                'updated_by' => $user_value_17,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_18,
                'created_by' => $user_value_18,
                'updated_by' => $user_value_18,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_19,
                'created_by' => $user_value_19,
                'updated_by' => $user_value_19,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
            [
                'heating_network_accident_id' => Str::Uuid()->toString(),
                'number_of_gusts' => 0,
                'owner_id' => $user_value_20,
                'created_by' => $user_value_20,
                'updated_by' => $user_value_20,
                'status_id' => $_ENV['STATUS_DEFAULT_OBJECT_ID'],
                'detection_date' => "2022-12-12 12:12:12",
                'elimination_date' => "2022-12-12 12:12:12",
                'mode' => ' ',
            ],
        ]);
    }
}
